#!/usr/bin/python3
'''beautifully formatted code that passes pycodestyle checks.'''


class PrettyMe:
	def __init__(self, value):
		self.value = value


	def display(self):
		print("Value: {self.value}")


	def main():
	example_instance = PrettyMe("I am a pretty code!")
	example_instance.display()


if __name__ == "__main__":
	main()
